#cloud-config

#YAML Para debian 12 con apache2 hardenizado

hostname: debian12-test-yaml
preserve_hostname: false

# Default user and SSH public keys

users:
  - name: caretaker
    groups: [sudo]
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 BLajsdfnewkojrqwopwdkasdj edson@ROG512LI

# Disable root SSH login and password authentication for SSH

ssh_pwauth: false
disable_root: true

# Update apt database and upgrade packages
package_update: true
package_upgrade: true

# Install packages
packages:
  - apache2
  - htop 
  - rsync 
  - zip 
  - git 
  - curl 
  - wget 
  - ufw
  - vim 
  - nano 
  - traceroute
  - dnsutils 
  - net-tools 
  - iputils-ping 
  - timeshift
  - fail2ban
  - software-properties-common 
  - ca-certificates
  - lsb-release
  - apt-transport-https

# Comands at boot
runcmd:
  - sudo systemctl enable apache
  - sudo ufw allow 22/tcp
  - sudo ufw allow 80/tcp
  - sudo ufw allow 443/tcp
  - sudo ufw enable
  
  - sudo curl -sSL https://packages.sury.org/php/README.txt | sudo bash -x
  - sudo apt update
  - sudo apt install php7.4 php7.4-mysql php7.4-xml php7.4-mbstring php7.4-curl
  - sudo systemctl restart apache 

  - sudo echo '<h1>¡Despliegue de Debian 12 con cloud-init Exitoso!</h1>' | sudo tee /var/www/html/index.html
  - sudo echo "cloud-init terminado en $(date)" | sudo tee -a /var/log/cloud-init-output.log

final_message: "La instancia Debian 12 ha sido configurada y está lista para aplicar configuración de fail2ban especificas"
